### ISSUE TITLE
Feature request: Allow Ollama server as a LLM provider

### ISSUE THREAD

**Issue by w00jay** [mayneyao/eidos#107]
Hi there,
would you be open to supporting Ollama server as an LLM provider?  I'm mostly curious if I can connect to a local Ollama LLM server w/ this feature.

**Comment by mayneyao** [comment]
It can work with any LLM provider compatible with OpenAI API.  In the settings(https://eidos.space/settings/ai ), add the LLM provider you need.  


For Ollama, follow the guidelines below to solve the cross-domain problem.

https://medium.com/dcoderai/how-to-handle-cors-settings-in-ollama-a-comprehensive-guide-ee2a5a1beef0

![image](https://github.com/mayneyao/eidos/assets/6588202/4744454c-3cd5-42f8-aba0-a6dd6400c010)

**Comment by w00jay** [comment]
Thank you for much for the instructions!  :+1:
