### ISSUE TITLE
Any plans for a docker image?

### ISSUE THREAD

**Issue by ovizii** [mayneyao/eidos#115]
Looks very nice. Do you have any plans to build and publish a docker image by any chance?

**Comment by mayneyao** [comment]
It's a PWA, just like https://squoosh.app/, with no web server. Everything runs inside your browser. No need for a Docker image

**Comment by ovizii** [comment]
Well, I get that part, but maybe I am still missing a crucial part of how to deploy it seeing that I am still confused.

Seeing that it runs in the browser, I'd like to get it up and running on a custom domain and put it behind a reverse proxy for HTTPS access.

So how would I do that or is it only meant to run in a local browser from a local deployment, not via any custom domain?

My assumption was that one needs a basic slim docker image and then executes the 5 steps of the “How to develop” inside the docker image.

**Comment by mayneyao** [comment]
Get it. I'm not good at Docker-related stuff, but creating an image should be simple. After building it, you'll get all static files in `dist` folder, which can be hosted by any server, such as Caddy or Nginx. 

the response headers need to be configured. see: https://github.com/mayneyao/eidos/blob/main/vercel.json 

PR Welcome

**Comment by ovizii** [comment]
Leave the issue open for a few days, I'll see if I can figure this out.

**Comment by mayneyao** [comment]
@ovizii  I just did some work on the `docker-image` branch, and you may want to try it.

https://github.com/mayneyao/eidos/tree/docker-image?tab=readme-ov-file#for-docker-users

**Comment by ovizii** [comment]
Thanks for giving it a try. Will have another look later.

I was looking for where/when eidos comes into play, but I can only spot this line:

`COPY ./dist /usr/share/nginx/html`

and I don't see any .dist folder anywhere.

**Comment by paulo-paes** [comment]
@ovizii check the PR readme.md. there is some instructions about how to run on docker

**Comment by mayneyao** [comment]
> Thanks for giving it a try. Will have another look later.
> 
> I was looking for where/when eidos comes into play, but I can only spot this line:
> 
> `COPY ./dist /usr/share/nginx/html`
> 
> and I don't see any .dist folder anywhere.

@ovizii  Sorry for that, I just finished the job. If there's anything wrong, please let me know
