### ISSUE TITLE
Cannot delete text on mobile

### ISSUE THREAD

**Issue by schmurian** [mayneyao/eidos#125]
OS version: Android 13

On Android I cannot delete text from the comments/details field.

A workaround is select all and delete.

Is there a way to fix this please?

![ResizedImage_2024-06-29_14-39-07_1246.png](https://github.com/mayneyao/eidos/assets/46840747/3dab7691-ae89-4508-8997-c7925fb757d3)

**Comment by mayneyao** [comment]
@schmurian This looks like a lexical bug, which was fixed after upgrading to 0.16.1. https://github.com/mayneyao/eidos/commit/2048823a1b11c2a78c69f696963ba74ee915bbd7 
I tested it on Android and it works normally. (version 0.5.1)

**Comment by schmurian** [comment]
Thank you, I was just able to confirm it.
