### ISSUE TITLE
Stuck at Create Space page

### ISSUE THREAD

**Issue by schmurian** [mayneyao/eidos#133]
When running the dev version locally (also in docker) I cannot create a new database (space)
![ResizedImage_2024-07-15_15-41-24_2201.png](https://github.com/user-attachments/assets/6b5daafd-993f-4fc1-b7fb-00c61258404e)

The page is stuck at the grey button "Creating"

**Comment by schmurian** [comment]
Also when uploading from an export from eidos.space it asks me to grant storing file permissions again.
I am redirected to the settings and can only select OPFS, not Native File System as I cannot enter a path:
![ResizedImage_2024-07-15_16-01-41_2629.png](https://github.com/user-attachments/assets/36083b6f-364f-45ee-8760-0fbf2e471711)

**Comment by mayneyao** [comment]
NFS only works in desktop browsers. because we need to select a folder, and this API is not supported on mobile browsers.
https://developer.mozilla.org/en-US/docs/Web/API/Window/showDirectoryPicker#browser_compatibility

The Arc browser loses persistent permissions after update, and I also encountered the problem of being unable to select folders; usually, restarting the browser resolves it. I'll keep track of this issue

**Comment by schmurian** [comment]
Also when uploading from an export from eidos.space it asks me to grant storing file permissions again.
I am redirected to the settings and can only select OPFS, not Native File System as I cannot enter a path:
![ResizedImage_2024-07-15_16-01-41_2629.png](https://github.com/user-attachments/assets/36083b6f-364f-45ee-8760-0fbf2e471711)

    Thank you for sharing. Makes sense. However I cannot use OPFS either. In both cases the button stays gray and no space will be created.

**Comment by schmurian** [comment]
Thank you for sharing. Makes sense. However I cannot use OPFS either. In both cases the button stays gray and no space will be created.

**Comment by mayneyao** [comment]
> Thank you for sharing. Makes sense. However I cannot use OPFS either. In both cases the button stays gray and no space will be created.

Is there any error information in the console?

**Comment by schmurian** [comment]
I will try, thank you. So I need to have https enabled to access spaces. Got it. Thank you for looking into it. I will confirm, once I've tested.

**Comment by schmurian** [comment]
I can confirm calling the app from https worked. thank you again!
