### ISSUE TITLE
Don't (or optionally) autohide blank Properties in the Gallery view

### ISSUE THREAD

**Issue by crisqyxw** [mayneyao/eidos#143]
For example, there's a Table like this:

![屏幕截图_20240729_192624](https://github.com/user-attachments/assets/30518a3a-6b4c-4764-b657-8be75f3779aa)

Below is what it looks like on Gallery View now:

![屏幕截图_20240729_192648](https://github.com/user-attachments/assets/4ea8517f-a6d4-427c-98dd-74524efa7eef)

Sometimes it may be necessary to edit properties in the gallery view (because that view is more intuitive and aesthetically pleasing), and always displaying a selection (or whatever) box for certain properties should be a nice feature, and shouldn't be difficult to implement?

**Comment by mayneyao** [comment]
That makes sense. I'll add the view configuration
